working_dir: "./tcav_class_test"
source_dir: "source_dir"
targets: [1]
concepts: ["Pos-EX_1"]
random_concepts: ["Neg-EX_1", "Neg-EX_2"]
num_random_exp: 3
label_path: "labels.txt"
bottlenecks: ['Mixed_5d', 'Conv2d_2a_3x3']
alphas: [0.1]
max_examples: 100
model: "inceptionv3"
# config: null
